//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstWrappingTest {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\SSmith\\Desktop\\Sandbox")]
        public string Path {
            get {
                return ((string)(this["Path"]));
            }
            set {
                this["Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("144.190.43.23")]
        public string SIP_SERVER_IP {
            get {
                return ((string)(this["SIP_SERVER_IP"]));
            }
            set {
                this["SIP_SERVER_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12507")]
        public string PTT_ID {
            get {
                return ((string)(this["PTT_ID"]));
            }
            set {
                this["PTT_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"eyJhbGciOiJSUzI1NiIsImtpZCI6ImtleTEiLCJ4NXQiOiJQNzA3dDNPb01RWlM0YWE5TmhPd1dTdkhlRzAifQ.eyJ1bnNJZCI6IjkwMTI1Iiwicm9sZSI6IjEyNTciLCJzZXJ2aWNlSWQiOiI5MDEyNSIsIm9yZ2FuaXphdGlvbiI6Im5pY2UiLCJleHAiOjE0OTg2NzIzOTYsInNjb3BlIjpbIm1zaV91bnNhcGlfYWZmaWxpYXRpb25tZ210LnJlYWQiLCJtc2lfdW5zYXBpX2FmZmlsaWF0aW9ubWdtdC53cml0ZSIsIm1zaV9jYWJfY2xpZW50LmFsbCIsIm1zaV91bnNhcGlfcHJlc2VuY2Uud2F0Y2giLCJtc2lfdW5zYXBpX2dyb3VwbWd0LnJlYWQiLCJtc2lfdW5zYXBpX2dyb3VwbWd0LndyaXRlIiwibXNpX3Vuc2FwaV9tZXNzYWdpbmciLCJtc2lfdW5zYXBpX2xvY2F0aW9uLndhdGNoIiwibXNpX3dhdmU3MDAwIl0sImNsaWVudF9pZCI6Im5pY2UiLCJpc3MiOiJodHRwczovL2lkbS5pbXcubW90b3JvbGFzb2x1dGlvbnMuY29tOjkwMzEiLCJqdGkiOiJQSzJnaXYzdUcxYnVOU0V5In0.DAXuAFmp9kzgvQDxNHLJGDq-Op8U5ggB3JRYljahVbxs99PBk5_sAsUcyj4DtdOkq1Ja1Xf1VBen33-Y4sjz5fNlO1PtQGqyVMi6Aa3yfUi38LQ-eSDpDP0EXz0RFNu7SJNAyFOt_9Ni0eO7yOq_rg2YM2OdCcxd1Il6N16HiipFkRe0aYYi4Ljc5rGzEN3BsPuJvwAQcvah0wmef1Pky9aR0p1aLWhWppXCD9IG7xB-Iw2wdcn0Gg25ybO8_n4oq_QUqgLPGtDauwGSF0OG78w1bX06kvvvUV-OLwRbK7D-__thrbVQg6aMfL1-15lvk8L1HJb2vE_0IVzmUWAnOQ")]
        public string LoginToken {
            get {
                return ((string)(this["LoginToken"]));
            }
            set {
                this["LoginToken"] = value;
            }
        }
    }
}
